/* =========================================================================
   REPLA-MUDANCES — Traduccions
   L'idioma base és el català: és el que hi ha escrit a l'HTML.

   LA CLAU ÉS LA FRASE EN CATALÀ, tal com surt a la pàgina. Si canvieu una
   frase de l'HTML i no la canvieu aquí, es quedarà en l'idioma base: lleig,
   però no enganya ningú.

   CRITERI (l'escriu qui tradueix, abans de la primera frase; és el que
   llegeixen els lots següents per no contradir-se):
   · TRACTAMENT: tu en català → «tú» en castellà (mai usted), «you» en anglès.
     To proper i directe, frases curtes, com parla una empresa petita de barri.
   · NO ES TRADUEIXEN: «Replà», «Replà Mudances», el telèfon 600 000 000,
     WhatsApp, Formspree, Brevo, Cloudflare, Turnstile, D1, aepd.es.
   · VOCABULARI: mudança → mudanza / move; guardamobles → guardamuebles /
     storage; petits transports → pequeños transportes / small removals;
     caixa → caja / box; manta → manta / blanket; permís d'aparcament →
     permiso de aparcamiento (reserva de vía pública) / parking permit.
   · Anglès britànic (lift, flat, removals). Preus amb «€» darrere.
   · Les etiquetes de les caixes de la furgoneta són una sola paraula curta.
   · MARCADORS DELS LEGALS: es queden igual a les tres versions (§8.I).

   El bloc entre TRAD:inici i TRAD:fi el reescriu
   `node <skill web-demo>/assets/i18n/i18n-prepara.mjs aplica`: els comentaris que s'hi
   posin es perden. El criteri va aquí dalt.
   ========================================================================= */

/* ── TRAD:inici ── generat per i18n-prepara.mjs aplica ── */
window.TRAD = {
  "igual": [
    "Replà",
    "© 2026 Replà Mudances",
    "M",
    "Marta G.",
    "J",
    "Jordi Puig",
    "L",
    "Laia Ferrer",
    "×",
    "Cloudflare Turnstile.",
    "Formspree.",
    "WhatsApp.",
    "km",
    "1 km",
    "60 km",
    "— km"
  ],
  "es": {
    "Avís legal de Replà Mudances.": "Aviso legal de Replà Mudances.",
    "Salta al contingut": "Saltar al contenido",
    "Replà Mudances, inici": "Replà Mudances, inicio",
    "Principal": "Principal",
    "Mudances": "Mudanzas",
    "Petits transports": "Pequeños transportes",
    "Guardamobles": "Guardamuebles",
    "Contacte": "Contacto",
    "Idioma de la pàgina": "Idioma de la página",
    "Calcula el preu": "Calcula el precio",
    "Menú": "Menú",
    "Avís legal": "Aviso legal",
    "Qui som": "Quiénes somos",
    "Aquesta web és de [RAÓ SOCIAL], amb NIF [NIF] i domicili a [DOMICILI]. Inscrita a [REGISTRE MERCANTIL]. Contacte: [CORREU DE CONTACTE], telèfon 600 000 000.": "Esta web es de [RAÓ SOCIAL], con NIF [NIF] y domicilio en [DOMICILI]. Inscrita en [REGISTRE MERCANTIL]. Contacto: [CORREU DE CONTACTE], teléfono 600 000 000.",
    "Ús de la web": "Uso de la web",
    "Qui fa servir aquesta web es compromet a fer-ho de bona fe i a no fer servir els formularis ni la calculadora per enviar informació falsa o de tercers sense el seu permís.": "Quien use esta web se compromete a hacerlo de buena fe y a no utilizar los formularios ni la calculadora para enviar información falsa o de terceros sin su permiso.",
    "Preus": "Precios",
    "Els preus que surten a la web i a la calculadora són orientatius i no són una oferta vinculant. El preu tancat es dona per escrit abans de cada servei.": "Los precios que aparecen en la web y en la calculadora son orientativos y no son una oferta vinculante. El precio cerrado se da por escrito antes de cada servicio.",
    "Propietat intel·lectual": "Propiedad intelectual",
    "Els textos, les imatges i el disseny d'aquesta web són de [RAÓ SOCIAL] o s'hi fan servir amb permís. Les tipografies tenen llicència SIL Open Font License.": "Los textos, las imágenes y el diseño de esta web son de [RAÓ SOCIAL] o se utilizan con permiso. Las tipografías tienen licencia SIL Open Font License.",
    "Responsabilitat": "Responsabilidad",
    "Intentem que la informació d'aquesta web sigui correcta i estigui al dia, però no podem garantir que no hi hagi cap error. Si en trobes un, ens el pots dir a [CORREU DE CONTACTE].": "Intentamos que la información de esta web sea correcta y esté actualizada, pero no podemos garantizar que no haya ningún error. Si encuentras uno, puedes decírnoslo en [CORREU DE CONTACTE].",
    "Llei aplicable": "Ley aplicable",
    "Aquesta web es regeix per la llei espanyola.": "Esta web se rige por la ley española.",
    "Mudances, petits transports i guardamobles. De dilluns a dissabte, de 8 a 19 h.": "Mudanzas, pequeños transportes y guardamuebles. De lunes a sábado, de 8 a 19 h.",
    "Serveis": "Servicios",
    "Escriu-nos": "Escríbenos",
    "Privacitat": "Privacidad",
    "Galetes": "Cookies",
    "Escriu-nos per WhatsApp": "Escríbenos por WhatsApp",
    "Avís legal · Replà Mudances": "Aviso legal · Replà Mudances",
    "Escriu-nos o truca'ns per a la teva mudança, un transport petit o el guardamobles.": "Escríbenos o llámanos para tu mudanza, un transporte pequeño o el guardamuebles.",
    "Explica'ns què et canvies i quan. Et contestem avui mateix o demà al matí.": "Cuéntanos qué te cambias y cuándo. Te contestamos hoy mismo o mañana por la mañana.",
    "Nom": "Nombre",
    "Correu": "Correo",
    "Què et cal?": "¿Qué necesitas?",
    "Fem servir aquestes dades només per contestar-te. Més informació a la": "Usamos estos datos solo para contestarte. Más información en la",
    "política de privacitat": "política de privacidad",
    "Envia el missatge": "Enviar el mensaje",
    "Més ràpid": "Más rápido",
    "Si ja saps què et canvies, la calculadora et dona un preu orientatiu en un minut i te'l prepara per enviar-nos per WhatsApp.": "Si ya sabes qué te cambias, la calculadora te da un precio orientativo en un minuto y te lo prepara para enviárnoslo por WhatsApp.",
    "O truca'ns de dilluns a dissabte, de 8 a 19 h.": "O llámanos de lunes a sábado, de 8 a 19 h.",
    "Contacte · Replà Mudances": "Contacto · Replà Mudances",
    "Guardamobles per setmanes o mesos, amb recollida i entrega a domicili. Per quan les dates de sortida i d'entrada no quadren.": "Guardamuebles por semanas o meses, con recogida y entrega a domicilio. Para cuando las fechas de salida y de entrada no coinciden.",
    "Per quan has de deixar el pis vell abans que et donin les claus del nou, o per a una reforma. Ho recollim, ho guardem i t'ho tornem.": "Para cuando tienes que dejar el piso viejo antes de que te den las llaves del nuevo, o para una reforma. Lo recogemos, lo guardamos y te lo devolvemos.",
    "Demana preu": "Pide precio",
    "Truca al 600 000 000": "Llama al 600 000 000",
    "Com funciona": "Cómo funciona",
    "Ho carreguem com en una mudança, ho guardem en caixes de fusta tancades i, quan ens ho dius, t'ho portem al pis nou.": "Lo cargamos como en una mudanza, lo guardamos en cajas de madera cerradas y, cuando nos lo dices, te lo llevamos al piso nuevo.",
    "Caixes de fusta tancades.": "Cajas de madera cerradas.",
    "Cada client té les seves. Ningú més hi toca": "Cada cliente tiene las suyas. Nadie más las toca",
    "Magatzem vigilat.": "Almacén vigilado.",
    "Sec, net i amb alarma": "Seco, limpio y con alarma",
    "Per setmanes o mesos.": "Por semanas o meses.",
    "Sense permanència mínima llarga": "Sin permanencia mínima larga",
    "Inventari.": "Inventario.",
    "Et donem la llista del que hi ha guardat": "Te damos la lista de lo que hay guardado",
    "Pots venir a buscar alguna cosa.": "Puedes venir a buscar algo.",
    "Avisant un dia abans": "Avisando un día antes",
    "Quant costa": "Cuánto cuesta",
    "Es paga pel volum i pel temps. Un pis de dues habitacions ocupa uns 20 metres cúbics.": "Se paga por el volumen y por el tiempo. Un piso de dos habitaciones ocupa unos 20 metros cúbicos.",
    "Preus orientatius": "Precios orientativos",
    "Per metre cúbic i mes": "Por metro cúbico y mes",
    "des de 9 €": "desde 9 €",
    "Pis de 2 habitacions (uns 20 m³)": "Piso de 2 habitaciones (unos 20 m³)",
    "des de 180 €/mes": "desde 180 €/mes",
    "Recollida i entrega": "Recogida y entrega",
    "com una mudança": "como una mudanza",
    "Preus d'exemple, IVA a part. Si ho combines amb la mudança, la recollida ja hi va inclosa.": "Precios de ejemplo, IVA aparte. Si lo combinas con la mudanza, la recogida ya va incluida.",
    "Preguntes que ens fan": "Preguntas que nos hacen",
    "Està assegurat el que guardeu?": "¿Está asegurado lo que guardáis?",
    "Sí, mentre és al magatzem i durant el transport.": "Sí, mientras está en el almacén y durante el transporte.",
    "Quant de temps mínim?": "¿Cuánto tiempo mínimo?",
    "Una setmana. Després es paga per mesos, i pots acabar quan vulguis avisant uns dies abans.": "Una semana. Después se paga por meses, y puedes acabar cuando quieras avisando unos días antes.",
    "Puc guardar-hi només uns quants mobles?": "¿Puedo guardar solo unos cuantos muebles?",
    "Sí. Si és poca cosa, ho compartim en una caixa gran amb separació, i pagues només el que ocupa.": "Sí. Si es poca cosa, lo compartimos en una caja grande con separación, y pagas solo lo que ocupa.",
    "Què no s'hi pot guardar?": "¿Qué no se puede guardar?",
    "Menjar, plantes, líquids inflamables ni res de valor com joies o diners.": "Comida, plantas, líquidos inflamables ni nada de valor como joyas o dinero.",
    "També fem": "También hacemos",
    "Mudances de pis i d'oficina": "Mudanzas de piso y de oficina",
    "Les dates no et quadren?": "¿Las fechas no te cuadran?",
    "Explica'ns quant de temps i què cal guardar, i et diem el preu.": "Cuéntanos cuánto tiempo y qué necesitas guardar, y te decimos el precio.",
    "Guardamobles · Replà Mudances": "Guardamuebles · Replà Mudances",
    "Mudances de pis i d'oficina, petits transports i guardamobles amb preu tancat per escrit. Calcula el preu de la teva mudança en un minut.": "Mudanzas de piso y de oficina, pequeños transportes y guardamuebles con precio cerrado por escrito. Calcula el precio de tu mudanza en un minuto.",
    "Ens emportem la casa i te la deixem muntada al pis nou.": "Nos llevamos la casa y te la dejamos montada en el piso nuevo.",
    "Mudances de pis i d'oficina amb preu tancat per escrit. Protegim l'escala, desmuntem i tornem a muntar, i ens emportem els cartrons.": "Mudanzas de piso y de oficina con precio cerrado por escrito. Protegemos la escalera, desmontamos y volvemos a montar, y nos llevamos los cartones.",
    "Calcula el preu en 1 minut": "Calcula el precio en 1 minuto",
    "Què et canvies?": "¿Qué te cambias?",
    "Tria-ho i en quatre preguntes més tens un preu orientatiu. Sense trucades ni esperar que et contestin.": "Elígelo y en cuatro preguntas más tienes un precio orientativo. Sin llamadas ni esperar a que te contesten.",
    "Estudi o 1 habitació": "Estudio o 1 habitación",
    "Unes 15–25 caixes i pocs mobles": "Unas 15–25 cajas y pocos muebles",
    "Pis de 2 o 3 habitacions": "Piso de 2 o 3 habitaciones",
    "El cas més habitual": "El caso más habitual",
    "Pis gran o casa": "Piso grande o casa",
    "4 habitacions o més": "4 habitaciones o más",
    "Només uns mobles": "Solo unos muebles",
    "Un sofà, un armari, una compra grossa": "Un sofá, un armario, una compra grande",
    "El dia de la mudança, hora a hora": "El día de la mudanza, hora a hora",
    "Un pis de dues habitacions a la mateixa ciutat. Abans del dia ja t'hem portat les caixes i hem demanat el permís per aparcar davant del portal.": "Un piso de dos habitaciones en la misma ciudad. Antes del día ya te hemos llevado las cajas y hemos pedido el permiso para aparcar delante del portal.",
    "Com treballem": "Cómo trabajamos",
    "Arribem i protegim": "Llegamos y protegemos",
    "Cartró a terra, mantes a la barana i a l'ascensor. La comunitat queda igual que estava.": "Cartón en el suelo, mantas en la barandilla y en el ascensor. La comunidad queda igual que estaba.",
    "Desmuntem el que no passa": "Desmontamos lo que no cabe",
    "Llits, armaris i taules grans. Els cargols van en una bossa enganxada a cada peça.": "Camas, armarios y mesas grandes. Los tornillos van en una bolsa pegada a cada pieza.",
    "Carreguem": "Cargamos",
    "Cada caixa porta escrita l'habitació on va. Els mobles, embolicats en mantes i lligats amb cinta.": "Cada caja lleva escrita la habitación adonde va. Los muebles, envueltos en mantas y atados con cinta.",
    "Descarreguem al pis nou": "Descargamos en el piso nuevo",
    "Tu ens dius on va cada cosa. Les caixes queden a la seva habitació, no totes al menjador.": "Tú nos dices dónde va cada cosa. Las cajas quedan en su habitación, no todas en el comedor.",
    "Muntem i col·loquem": "Montamos y colocamos",
    "Llits muntats, armaris a lloc i la tele penjada si ens ho has demanat.": "Camas montadas, armarios en su sitio y la tele colgada si nos lo has pedido.",
    "Ens ho emportem tot": "Nos lo llevamos todo",
    "Cartrons, plàstics i el que no vulguis. Tu et quedes amb les claus i el pis net.": "Cartones, plásticos y lo que no quieras. Tú te quedas con las llaves y el piso limpio.",
    "Què inclou el preu": "Qué incluye el precio",
    "El que signem abans de la mudança": "Lo que firmamos antes de la mudanza",
    "Preu tancat per escrit": "Precio cerrado por escrito",
    "Si el dia hi ha les coses que vam dir, pagues el que vam dir.": "Si el día hay las cosas que dijimos, pagas lo que dijimos.",
    "Assegurança de la càrrega": "Seguro de la carga",
    "Si es trenca alguna cosa per culpa nostra, la paguem nosaltres.": "Si se rompe algo por nuestra culpa, lo pagamos nosotros.",
    "Escala i ascensor protegits": "Escalera y ascensor protegidos",
    "Als dos edificis, el de sortida i el d'arribada.": "En los dos edificios, el de salida y el de llegada.",
    "Permís d'aparcament": "Permiso de aparcamiento",
    "El demanem nosaltres a l'ajuntament, amb temps.": "Lo pedimos nosotros al ayuntamiento, con tiempo.",
    "Equip propi": "Equipo propio",
    "Els mateixos que venen a veure el pis són els que fan la mudança.": "Los mismos que vienen a ver el piso son los que hacen la mudanza.",
    "Hora d'arribada concreta": "Hora de llegada concreta",
    "Una franja de 30 minuts, no «al matí».": "Una franja de 30 minutos, no «por la mañana».",
    "No hi entra:": "No incluye:",
    "l'elevador exterior quan un moble no passa per l'escala, ni el guardamobles. Si cal, t'ho diem abans i ho veus escrit al pressupost.": "el elevador exterior cuando un mueble no cabe por la escalera, ni el guardamuebles. Si hace falta, te lo decimos antes y lo ves escrito en el presupuesto.",
    "Signatura del client": "Firma del cliente",
    "Què fem": "Qué hacemos",
    "Dos operaris traslladen un sofà embolicat amb una manta pel vestíbul d'un edifici": "Dos operarios trasladan un sofá envuelto con una manta por el vestíbulo de un edificio",
    "Del pis vell al nou, amb tot desmuntat, protegit i tornat a muntar.": "Del piso viejo al nuevo, con todo desmontado, protegido y vuelto a montar.",
    "Veure mudances": "Ver mudanzas",
    "Furgoneta petita amb un armari embolicat i caixes lligades amb cintes": "Furgoneta pequeña con un armario envuelto y cajas atadas con cintas",
    "Un sofà, un armari o la compra de la botiga de mobles.": "Un sofá, un armario o la compra de la tienda de muebles.",
    "Veure transports": "Ver transportes",
    "Magatzem net amb caixes de fusta sobre palets i mobles tapats": "Almacén limpio con cajas de madera sobre palets y muebles tapados",
    "Per quan les dates de sortida i d'entrada no quadren.": "Para cuando las fechas de salida y de entrada no coinciden.",
    "Veure guardamobles": "Ver guardamuebles",
    "Serveis que s'hi poden afegir": "Servicios que se pueden añadir",
    "També:": "También:",
    "Embalatge de tota la casa": "Embalaje de toda la casa",
    "Desmuntar i muntar mobles": "Desmontar y montar muebles",
    "Buidatge de pisos": "Vaciado de pisos",
    "Elevador exterior": "Elevador exterior",
    "Mudances fetes": "Mudanzas hechas",
    "Furgoneta carregada: caixes apilades i mobles embolicats amb mantes i cintes": "Furgoneta cargada: cajas apiladas y muebles envueltos con mantas y cintas",
    "Pis de 3 habitacions.": "Piso de 3 habitaciones.",
    "Tot en un sol viatge.": "Todo en un solo viaje.",
    "Escala estreta protegida amb cartró i mantes a la barana, amb caixes al replà": "Escalera estrecha protegida con cartón y mantas en la barandilla, con cajas en el rellano",
    "Un quart sense ascensor.": "Un cuarto sin ascensor.",
    "Barana i esglaons protegits.": "Barandilla y escalones protegidos.",
    "Oficina durant el trasllat, amb cadires embolicades i caixes en un carro": "Oficina durante el traslado, con sillas envueltas y cajas en un carro",
    "Oficina de 12 llocs.": "Oficina de 12 puestos.",
    "Fet en dissabte.": "Hecho en sábado.",
    "Elevador exterior aixecat fins a un balcó amb un sofà embolicat": "Elevador exterior levantado hasta un balcón con un sofá envuelto",
    "Un sofà que no passava per l'escala.": "Un sofá que no cabía por la escalera.",
    "Per la finestra.": "Por la ventana.",
    "Caixa de cartró amb plats i gots embolicats amb paper": "Caja de cartón con platos y vasos envueltos con papel",
    "La cuina.": "La cocina.",
    "Cada got, embolicat a part.": "Cada vaso, envuelto por separado.",
    "Pis buit i escombrat després de la mudança, amb sol entrant per la finestra": "Piso vacío y barrido después de la mudanza, con sol entrando por la ventana",
    "El pis vell.": "El piso viejo.",
    "Buit i escombrat per tornar les claus.": "Vacío y barrido para devolver las llaves.",
    "Dos operaris d'esquena camí de la furgoneta, un empenyent un carretó amb caixes": "Dos operarios de espaldas camino de la furgoneta, uno empujando un carretón con cajas",
    "Primera mudança del dia, a les vuit.": "Primera mudanza del día, a las ocho.",
    "Som la Pau i la Núria": "Somos Pau y Núria",
    "Vam començar amb una furgoneta llogada i les mudances dels amics. Ara som més i tenim camions propis, però ho seguim fent igual: veiem el pis abans, et diem el preu per escrit i el dia hi som a l'hora.": "Empezamos con una furgoneta alquilada y las mudanzas de los amigos. Ahora somos más y tenemos camiones propios, pero lo seguimos haciendo igual: vemos el piso antes, te decimos el precio por escrito y el día estamos a la hora.",
    "La Núria fa els pressupostos i organitza els dies. La Pau porta l'equip i és qui hi ha el dia de la mudança, de la primera caixa a l'última.": "Núria hace los presupuestos y organiza los días. Pau lleva el equipo y es quien está el día de la mudanza, desde la primera caja hasta la última.",
    "Què diuen de nosaltres": "Qué dicen de nosotros",
    "Ressenyes d'exemple": "Reseñas de ejemplo",
    "fa 2 setmanes": "hace 2 semanas",
    "5 de 5 estrelles": "5 de 5 estrellas",
    "Un tercer sense ascensor a un quart sense ascensor, i a les dues havien acabat. El preu va ser el del paper, ni un euro més.": "Un tercero sin ascensor a un cuarto sin ascensor, y a las dos habían terminado. El precio fue el del papel, ni un euro más.",
    "fa 1 mes": "hace 1 mes",
    "Vam traslladar l'oficina un dissabte i el dilluns tothom tenia l'ordinador endollat. Les caixes anaven marcades per taula.": "Trasladamos la oficina un sábado y el lunes todo el mundo tenía el ordenador enchufado. Las cajas iban marcadas por mesa.",
    "fa 3 mesos": "hace 3 meses",
    "4 de 5 estrelles": "4 de 5 estrellas",
    "Van arribar vint minuts tard per un tall al carrer, però m'havien avisat per WhatsApp. Tot arribat sencer, fins i tot el mirall gran.": "Llegaron veinte minutos tarde por un corte en la calle, pero me habían avisado por WhatsApp. Todo llegó entero, hasta el espejo grande.",
    "Tens data de claus? Mira quant et costarà.": "¿Tienes fecha de llaves? Mira cuánto te costará.",
    "Cinc preguntes, un preu orientatiu i el resum a punt per enviar-nos per WhatsApp.": "Cinco preguntas, un precio orientativo y el resumen listo para enviárnoslo por WhatsApp.",
    "Foto ampliada": "Foto ampliada",
    "Tanca": "Cerrar",
    "Replà Mudances · Mudances de pis, petits transports i guardamobles": "Replà Mudances · Mudanzas de piso, pequeños transportes y guardamuebles",
    "Mudances de pis i d'oficina amb preu tancat per escrit, assegurança de la càrrega, muntatge de mobles i permís d'aparcament inclosos.": "Mudanzas de piso y de oficina con precio cerrado por escrito, seguro de la carga, montaje de muebles y permiso de aparcamiento incluidos.",
    "Del pis vell al nou en un dia, amb els mobles muntats i les caixes a la seva habitació.": "Del piso viejo al nuevo en un día, con los muebles montados y las cajas en su habitación.",
    "Una mudança de pis sencera, o la d'una oficina petita un dissabte perquè el dilluns es pugui treballar.": "Una mudanza de piso entera, o la de una oficina pequeña un sábado para que el lunes se pueda trabajar.",
    "Visita o videotrucada.": "Visita o videollamada.",
    "Veiem què hi ha i com són els accessos abans de donar-te el preu": "Vemos qué hay y cómo son los accesos antes de darte el precio",
    "Protecció.": "Protección.",
    "Cartró a terra i mantes a l'escala i a l'ascensor, als dos edificis": "Cartón en el suelo y mantas en la escalera y en el ascensor, en los dos edificios",
    "Desmuntar i muntar.": "Desmontar y montar.",
    "Llits, armaris, taules i el que no passi sencer per la porta": "Camas, armarios, mesas y lo que no quepa entero por la puerta",
    "Càrrega amb mantes i cintes.": "Carga con mantas y cintas.",
    "Res va solt dins del camió": "Nada va suelto dentro del camión",
    "Permís d'aparcament.": "Permiso de aparcamiento.",
    "El demanem nosaltres amb el temps que demana cada ajuntament": "Lo pedimos nosotros con el tiempo que pide cada ayuntamiento",
    "Retirada de cartrons.": "Retirada de cartones.",
    "Quan acabem, ens emportem el material d'embalar": "Cuando acabamos, nos llevamos el material de embalar",
    "Com ho fem": "Cómo lo hacemos",
    "Ens expliques què et canvies": "Nos cuentas qué te cambias",
    "Amb la calculadora, per WhatsApp o per telèfon. Si vols, fem una videotrucada i ens ensenyes el pis.": "Con la calculadora, por WhatsApp o por teléfono. Si quieres, hacemos una videollamada y nos enseñas el piso.",
    "Et donem el preu per escrit": "Te damos el precio por escrito",
    "Amb tot el que inclou i el que no. Si hi ha un moble que no passa per l'escala, ja ho diem aquí.": "Con todo lo que incluye y lo que no. Si hay un mueble que no cabe por la escalera, ya lo decimos aquí.",
    "Et portem les caixes": "Te llevamos las cajas",
    "Uns dies abans, perquè puguis anar embalant. O ho embalem nosaltres.": "Unos días antes, para que puedas ir embalando. O lo embalamos nosotros.",
    "El dia de la mudança": "El día de la mudanza",
    "Hi arribem a l'hora pactada i no marxem fins que els mobles estan muntats.": "Llegamos a la hora pactada y no nos vamos hasta que los muebles están montados.",
    "Depèn sobretot de quantes coses hi ha i de com són els accessos. La distància pesa menys del que sembla.": "Depende sobre todo de cuántas cosas hay y de cómo son los accesos. La distancia pesa menos de lo que parece.",
    "Calcula el teu preu": "Calcula tu precio",
    "Preus orientatius dins la mateixa ciutat": "Precios orientativos dentro de la misma ciudad",
    "des de 260 €": "desde 260 €",
    "des de 510 €": "desde 510 €",
    "des de 880 €": "desde 880 €",
    "Oficina petita": "Oficina pequeña",
    "segons els llocs de treball": "según los puestos de trabajo",
    "Preus d'exemple, IVA a part. Sense ascensor o amb embalatge i muntatge, el preu puja. El tancat te'l donem per escrit.": "Precios de ejemplo, IVA aparte. Sin ascensor o con embalaje y montaje, el precio sube. El cerrado te lo damos por escrito.",
    "El preu és tancat?": "¿El precio es cerrado?",
    "Sí. Te'l donem per escrit després de veure el pis o una videotrucada. Només canvia si el dia hi ha coses que no hi eren, i en aquest cas t'ho diem abans de carregar-les.": "Sí. Te lo damos por escrito después de ver el piso o una videollamada. Solo cambia si el día hay cosas que no estaban, y en ese caso te lo decimos antes de cargarlas.",
    "I si es trenca alguna cosa?": "¿Y si se rompe algo?",
    "Tota la càrrega va assegurada. Si es trenca o es fa malbé alguna cosa per culpa nostra, la reparem o la paguem. Ho deixem escrit al pressupost.": "Toda la carga va asegurada. Si se rompe o se estropea algo por nuestra culpa, lo reparamos o lo pagamos. Lo dejamos escrito en el presupuesto.",
    "Qui demana el permís per aparcar el camió?": "¿Quién pide el permiso para aparcar el camión?",
    "Nosaltres. Cada ajuntament té els seus terminis (sovint una setmana), per això és millor reservar amb temps.": "Nosotros. Cada ayuntamiento tiene sus plazos (a menudo una semana), por eso es mejor reservar con tiempo.",
    "I si no hi ha ascensor o el sofà no passa per l'escala?": "¿Y si no hay ascensor o el sofá no cabe por la escalera?",
    "Sense ascensor ho pugem a peu i ja ho comptem al preu. Si un moble no passa, fem servir un elevador exterior per la finestra o el balcó, i t'ho diem al pressupost.": "Sin ascensor lo subimos a pie y ya lo contamos en el precio. Si un mueble no cabe, usamos un elevador exterior por la ventana o el balcón, y te lo decimos en el presupuesto.",
    "Amb quanta antelació he de reservar?": "¿Con cuánta antelación tengo que reservar?",
    "Amb dues o tres setmanes vas bé. A final de mes i a l'estiu s'omple abans. Si és urgent, pregunta: de vegades hi ha forats.": "Con dos o tres semanas vas bien. A final de mes y en verano se llena antes. Si es urgente, pregunta: a veces hay huecos.",
    "Us podeu endur el que no vull?": "¿Os podéis llevar lo que no quiero?",
    "Sí. Ens emportem mobles i trastos que no vulguis traslladar i els portem al punt verd o a entitats que els aprofiten. Té un cost a part.": "Sí. Nos llevamos muebles y trastos que no quieras trasladar y los llevamos al punto verde o a entidades que los aprovechan. Tiene un coste aparte.",
    "Tens data de claus?": "¿Tienes fecha de llaves?",
    "Calcula el preu orientatiu i envia'ns el resum per WhatsApp.": "Calcula el precio orientativo y envíanos el resumen por WhatsApp.",
    "Mudances de pis i d'oficina · Replà Mudances": "Mudanzas de piso y oficina · Replà Mudances",
    "Transport de mobles solts i compres grans: un sofà, un armari o la compra de la botiga de mobles, pujat i muntat a casa.": "Transporte de muebles sueltos y compras grandes: un sofá, un armario o la compra de la tienda de muebles, subido y montado en casa.",
    "Un sofà, un armari o la compra de la botiga de mobles. Ho recollim, ho pugem i, si cal, ho muntem.": "Un sofá, un armario o la compra de la tienda de muebles. Lo recogemos, lo subimos y, si hace falta, lo montamos.",
    "Per a quan no és una mudança": "Para cuando no es una mudanza",
    "Quan només són uns quants mobles, no cal llogar una furgoneta ni demanar favors a ningú un dissabte.": "Cuando solo son unos cuantos muebles, no hace falta alquilar una furgoneta ni pedir favores a nadie un sábado.",
    "Mobles solts.": "Muebles sueltos.",
    "Un sofà, un llit, una calaixera o l'armari de l'àvia": "Un sofá, una cama, una cómoda o el armario de la abuela",
    "Compres grans.": "Compras grandes.",
    "Recollim a la botiga o al magatzem i t'ho portem a casa": "Recogemos en la tienda o en el almacén y te lo llevamos a casa",
    "Muntatge.": "Montaje.",
    "Els mobles de paquet pla te'ls deixem muntats": "Los muebles de embalaje plano te los dejamos montados",
    "Entre pisos del mateix edifici.": "Entre pisos del mismo edificio.",
    "També, i amb el mateix compte que en una mudança": "También, y con el mismo cuidado que en una mudanza",
    "Un transport petit dins la mateixa ciutat surt a partir de 80 €. Depèn de quantes peces són, de la distància i de si hi ha ascensor.": "Un transporte pequeño dentro de la misma ciudad sale a partir de 80 €. Depende de cuántas piezas son, de la distancia y de si hay ascensor.",
    "Exemples orientatius": "Ejemplos orientativos",
    "Un sofà, mateixa ciutat, amb ascensor": "Un sofá, misma ciudad, con ascensor",
    "des de 80 €": "desde 80 €",
    "Compra d'una botiga de mobles, muntada": "Compra de una tienda de muebles, montada",
    "des de 150 €": "desde 150 €",
    "Tres o quatre mobles, sense ascensor": "Tres o cuatro muebles, sin ascensor",
    "des de 180 €": "desde 180 €",
    "Preus d'exemple, IVA a part.": "Precios de ejemplo, IVA aparte.",
    "Veniu per un sol moble?": "¿Venís por un solo mueble?",
    "Sí. Si és dins la zona, venim per un sol moble. Ho veuràs al preu.": "Sí. Si está dentro de la zona, venimos por un solo mueble. Lo verás en el precio.",
    "Podeu recollir-ho a la botiga?": "¿Podéis recogerlo en la tienda?",
    "Sí. Ens passes el número de comanda i l'hora de recollida, i ho anem a buscar nosaltres.": "Sí. Nos pasas el número de pedido y la hora de recogida, y vamos a buscarlo nosotros.",
    "Ho pugeu fins a dins del pis?": "¿Lo subís hasta dentro del piso?",
    "Sí, fins a l'habitació on va. No ho deixem al portal.": "Sí, hasta la habitación donde va. No lo dejamos en el portal.",
    "Munteu mobles de paquet pla?": "¿Montáis muebles de embalaje plano?",
    "Sí, i ens emportem els cartrons. Si ja el tens a casa, també et podem venir només a muntar.": "Sí, y nos llevamos los cartones. Si ya lo tienes en casa, también podemos venir solo a montarlo.",
    "Només són uns mobles?": "¿Solo son unos muebles?",
    "En un minut saps quant et costarà portar-los.": "En un minuto sabes cuánto te costará llevarlos.",
    "Petits transports · Replà Mudances": "Pequeños transportes · Replà Mudances",
    "Política de galetes de Replà Mudances.": "Política de cookies de Replà Mudances.",
    "Política de galetes": "Política de cookies",
    "Galetes nostres": "Cookies propias",
    "Aquesta web no fa servir galetes pròpies ni d'analítica. Les tipografies s'allotgen a la mateixa web i no es demanen a cap servei extern.": "Esta web no usa cookies propias ni de analítica. Las tipografías se alojan en la misma web y no se piden a ningún servicio externo.",
    "Emmagatzematge del navegador": "Almacenamiento del navegador",
    "La calculadora guarda les teves respostes a l'emmagatzematge de sessió del navegador perquè no les perdis si recarregues la pàgina. S'esborra sol quan tanques la pestanya i no s'envia enlloc.": "La calculadora guarda tus respuestas en el almacenamiento de sesión del navegador para que no las pierdas si recargas la página. Se borra solo cuando cierras la pestaña y no se envía a ningún sitio.",
    "Serveis de tercers": "Servicios de terceros",
    "Només a la calculadora, quan arribes al pas del correu, per comprovar que no ets un robot. Pot fer servir dades tècniques del navegador.": "Solo en la calculadora, cuando llegas al paso del correo, para comprobar que no eres un robot. Puede usar datos técnicos del navegador.",
    "Només si envies el formulari de contacte, i només rep el que hi escrius.": "Solo si envías el formulario de contacto, y solo recibe lo que escribes en él.",
    "Els botons de WhatsApp obren l'aplicació o la web de WhatsApp. A partir d'aquí s'aplica la política de WhatsApp.": "Los botones de WhatsApp abren la aplicación o la web de WhatsApp. A partir de aquí se aplica la política de WhatsApp.",
    "Política de galetes · Replà Mudances": "Política de cookies · Replà Mudances",
    "Política de privacitat de Replà Mudances.": "Política de privacidad de Replà Mudances.",
    "Política de privacitat": "Política de privacidad",
    "Responsable": "Responsable",
    "[RAÓ SOCIAL], NIF [NIF], [DOMICILI]. Contacte per a qüestions de privacitat: [CORREU DE CONTACTE].": "[RAÓ SOCIAL], NIF [NIF], [DOMICILI]. Contacto para cuestiones de privacidad: [CORREU DE CONTACTE].",
    "Quines dades recollim i per a què": "Qué datos recogemos y para qué",
    "Formulari de contacte.": "Formulario de contacto.",
    "Nom, correu i el missatge, per contestar-te. El formulari el gestiona Formspree, Inc. (Estats Units), que actua com a encarregat del tractament i ens fa arribar el missatge.": "Nombre, correo y el mensaje, para contestarte. El formulario lo gestiona Formspree, Inc. (Estados Unidos), que actúa como encargado del tratamiento y nos hace llegar el mensaje.",
    "Calculadora de preu.": "Calculadora de precio.",
    "Per ensenyar-te el preu et demanem el correu i t'hi enviem un codi de verificació amb Brevo (Sendinblue SAS, Unió Europea). El codi es guarda xifrat un màxim de 10 minuts.": "Para enseñarte el precio te pedimos el correo y te enviamos un código de verificación con Brevo (Sendinblue SAS, Unión Europea). El código se guarda cifrado un máximo de 10 minutos.",
    "Per comprovar que qui fa servir la calculadora no és un robot, fem servir Cloudflare Turnstile, que pot tractar dades tècniques com la teva adreça IP. Només es carrega quan arribes al pas del correu.": "Para comprobar que quien usa la calculadora no es un robot, usamos Cloudflare Turnstile, que puede tratar datos técnicos como tu dirección IP. Solo se carga cuando llegas al paso del correo.",
    "Quan verifiques el codi, guardem el correu, les respostes de la calculadora, el preu orientatiu, l'idioma de la pàgina i la data en una base de dades de Cloudflare (D1), per poder-te contactar sobre aquesta mudança. T'enviem un correu amb el resum i ens arriba un avís a nosaltres, tots dos amb Brevo.": "Cuando verificas el código, guardamos el correo, las respuestas de la calculadora, el precio orientativo, el idioma de la página y la fecha en una base de datos de Cloudflare (D1), para poder contactarte sobre esta mudanza. Te enviamos un correo con el resumen y a nosotros nos llega un aviso, ambos con Brevo.",
    "Base legal": "Base legal",
    "El teu consentiment, quan ens escrius o fas servir la calculadora, i l'interès a contestar la sol·licitud que ens fas.": "Tu consentimiento, cuando nos escribes o usas la calculadora, y el interés en contestar la solicitud que nos haces.",
    "Quant de temps les guardem": "Cuánto tiempo las guardamos",
    "El temps necessari per atendre la teva sol·licitud i, com a màxim, un any des de l'últim contacte si no n'hi ha cap servei contractat.": "El tiempo necesario para atender tu solicitud y, como máximo, un año desde el último contacto si no hay ningún servicio contratado.",
    "Els teus drets": "Tus derechos",
    "Pots demanar accedir a les teves dades, corregir-les, esborrar-les, limitar-ne o oposar-te al tractament i portar-les a un altre lloc escrivint a [CORREU DE CONTACTE]. Si creus que no les tractem bé, pots reclamar a l'Agència Espanyola de Protecció de Dades (aepd.es).": "Puedes pedir acceder a tus datos, corregirlos, borrarlos, limitar su tratamiento u oponerte a él, y llevártelos a otro sitio escribiendo a [CORREU DE CONTACTE]. Si crees que no los tratamos bien, puedes reclamar a la Agencia Española de Protección de Datos (aepd.es).",
    "Política de privacitat · Replà Mudances": "Política de privacidad · Replà Mudances",
    "Calcula en un minut quant et pot costar la mudança o el transport dels teus mobles. Sense compromís.": "Calcula en un minuto cuánto te puede costar la mudanza o el transporte de tus muebles. Sin compromiso.",
    "Enrere": "Atrás",
    "Progrés": "Progreso",
    "Les teves respostes": "Tus respuestas",
    "Calcula el preu en 1 minut. Sense compromís.": "Calcula el precio en 1 minuto. Sin compromiso.",
    "Quants quilòmetres hi ha entre les dues adreces?": "¿Cuántos kilómetros hay entre las dos direcciones?",
    "Si és al mateix poble o barri, deixa-ho entre 1 i 5.": "Si es en el mismo pueblo o barrio, déjalo entre 1 y 5.",
    "Quilòmetres": "Kilómetros",
    "Continua": "Continuar",
    "Com són els accessos?": "¿Cómo son los accesos?",
    "Pensa en el pis d'on surts i en el pis on vas.": "Piensa en el piso de donde sales y en el piso adonde vas.",
    "Hi ha ascensor als dos llocs": "Hay ascensor en los dos sitios",
    "O és una planta baixa.": "O es una planta baja.",
    "Escales en un dels dos": "Escaleras en uno de los dos",
    "A l'altre hi ha ascensor.": "En el otro hay ascensor.",
    "Escales als dos llocs": "Escaleras en los dos sitios",
    "Sense ascensor enlloc.": "Sin ascensor en ningún sitio.",
    "Què vols que fem nosaltres?": "¿Qué quieres que hagamos nosotros?",
    "Només el transport": "Solo el transporte",
    "Tu embales i desmuntes. Nosaltres carreguem i ho portem.": "Tú embalas y desmontas. Nosotros cargamos y lo llevamos.",
    "També embalar i muntar": "También embalar y montar",
    "Embalem, desmuntem i tornem a muntar els mobles.": "Embalamos, desmontamos y volvemos a montar los muebles.",
    "Tot, fins i tot desembalar": "Todo, incluso desembalar",
    "Arribes al pis nou i ja està tot al seu lloc.": "Llegas al piso nuevo y ya está todo en su sitio.",
    "Quan et va bé?": "¿Cuándo te va bien?",
    "Tinc una data fixa": "Tengo una fecha fija",
    "Soc flexible": "Soy flexible",
    "Si ens deixes triar el dia, surt més barat.": "Si nos dejas elegir el día, sale más barato.",
    "Només miro preus": "Solo estoy mirando precios",
    "El teu preu ja està calculat": "Tu precio ya está calculado",
    "Verifica el correu per veure'l. T'hi enviarem també el resum.": "Verifica el correo para verlo. También te enviaremos allí el resumen.",
    "El teu correu": "Tu correo",
    "Envia'm el codi": "Envíame el código",
    "Guardem el correu i les respostes per poder-te contactar sobre aquesta mudança. Més informació a la": "Guardamos el correo y las respuestas para poder contactarte sobre esta mudanza. Más información en la",
    "Escriu el codi": "Escribe el código",
    "L'hem enviat a": "Lo hemos enviado a",
    ". Caduca d'aquí a 10 minuts.": ". Caduca dentro de 10 minutos.",
    "Codi de 6 xifres": "Código de 6 cifras",
    "Xifra 1": "Cifra 1",
    "Xifra 2": "Cifra 2",
    "Xifra 3": "Cifra 3",
    "Xifra 4": "Cifra 4",
    "Xifra 5": "Cifra 5",
    "Xifra 6": "Cifra 6",
    "Torna a enviar el codi": "Reenviar el código",
    "Canvia el correu": "Cambiar el correo",
    "Preu orientatiu de la teva mudança": "Precio orientativo de tu mudanza",
    "IVA a part. El preu tancat te'l donem per escrit abans del dia de la mudança.": "IVA aparte. El precio cerrado te lo damos por escrito antes del día de la mudanza.",
    "També t'hem enviat aquest resum al correu.": "También te hemos enviado este resumen al correo.",
    "Envia'ns la mudança per WhatsApp": "Envíanos la mudanza por WhatsApp",
    "S'obrirà WhatsApp amb el resum ja escrit. Només l'has d'enviar.": "Se abrirá WhatsApp con el resumen ya escrito. Solo tienes que enviarlo.",
    "Prefereixo que m'escriviu": "Prefiero que me escribáis",
    "Calcula una altra mudança": "Calcula otra mudanza",
    "La furgoneta és buida. Respon i s'anirà omplint.": "La furgoneta está vacía. Responde y se irá llenando.",
    "Calcula el preu de la mudança · Replà Mudances": "Calcula el precio de la mudanza · Replà Mudances",
    "Roba": "Ropa",
    "Cuina": "Cocina",
    "Llibres": "Libros",
    "Menjador": "Comedor",
    "Bany": "Baño",
    "Llençols": "Sábanas",
    "Joguines": "Juguetes",
    "Traster": "Trastero",
    "Sofà": "Sofá",
    "Armari": "Armario",
    "Eines": "Herramientas",
    "Paper": "Papel",
    "Mantes": "Mantas",
    "Carregada i a punt per sortir.": "Cargada y lista para salir.",
    "Caixes a la furgoneta:": "Cajas en la furgoneta:",
    "Canvia aquesta resposta": "Cambiar esta respuesta",
    "Escriu un correu vàlid, per exemple nom@gmail.com.": "Escribe un correo válido, por ejemplo nombre@gmail.com.",
    "Espera un moment que acabi la comprovació de seguretat i torna-hi.": "Espera un momento a que acabe la comprobación de seguridad e inténtalo de nuevo.",
    "Enviant…": "Enviando…",
    "Has demanat massa codis. Espera uns minuts i torna-hi.": "Has pedido demasiados códigos. Espera unos minutos e inténtalo de nuevo.",
    "No hem pogut confirmar que no ets un robot. Torna-hi.": "No hemos podido confirmar que no eres un robot. Inténtalo de nuevo.",
    "No hem pogut enviar el codi. Torna-hi d'aquí a uns minuts.": "No hemos podido enviar el código. Inténtalo de nuevo dentro de unos minutos.",
    "El codi ha caducat. Demana'n un de nou.": "El código ha caducado. Pide uno nuevo.",
    "Massa intents. Demana un codi nou.": "Demasiados intentos. Pide un código nuevo.",
    "El codi no és correcte. Revisa'l i torna a escriure'l.": "El código no es correcto. Revísalo y vuelve a escribirlo.",
    "No hem pogut comprovar el codi. Torna-hi.": "No hemos podido comprobar el código. Inténtalo de nuevo.",
    "Hola, vull fer una mudança. He fet servir la calculadora de la web: {resum}. Preu orientatiu: {rang}. Em podeu dir un dia?": "Hola, quiero hacer una mudanza. He usado la calculadora de la web: {resum}. Precio orientativo: {rang}. ¿Podéis decirme un día?",
    "Escriu el teu nom.": "Escribe tu nombre.",
    "Escriu un correu vàlid.": "Escribe un correo válido.",
    "Explica'ns què et cal.": "Cuéntanos qué necesitas.",
    "Rebut. Et contestem avui mateix o demà al matí.": "Recibido. Te contestamos hoy mismo o mañana por la mañana.",
    "No s'ha pogut enviar. Truca'ns al 600 000 000 i t'atenem directament.": "No se ha podido enviar. Llámanos al 600 000 000 y te atendemos directamente."
  },
  "en": {
    "Avís legal de Replà Mudances.": "Legal notice for Replà Mudances.",
    "Salta al contingut": "Skip to content",
    "Replà Mudances, inici": "Replà Mudances, home",
    "Principal": "Main",
    "Mudances": "Removals",
    "Petits transports": "Small removals",
    "Guardamobles": "Storage",
    "Contacte": "Contact",
    "Idioma de la pàgina": "Page language",
    "Calcula el preu": "Calculate the price",
    "Menú": "Menu",
    "Avís legal": "Legal notice",
    "Qui som": "About us",
    "Aquesta web és de [RAÓ SOCIAL], amb NIF [NIF] i domicili a [DOMICILI]. Inscrita a [REGISTRE MERCANTIL]. Contacte: [CORREU DE CONTACTE], telèfon 600 000 000.": "This website belongs to [RAÓ SOCIAL], with NIF [NIF] and registered address at [DOMICILI]. Registered at [REGISTRE MERCANTIL]. Contact: [CORREU DE CONTACTE], phone 600 000 000.",
    "Ús de la web": "Use of the website",
    "Qui fa servir aquesta web es compromet a fer-ho de bona fe i a no fer servir els formularis ni la calculadora per enviar informació falsa o de tercers sense el seu permís.": "Anyone using this website agrees to do so in good faith and not to use the forms or the calculator to send false information or information about third parties without their permission.",
    "Preus": "Prices",
    "Els preus que surten a la web i a la calculadora són orientatius i no són una oferta vinculant. El preu tancat es dona per escrit abans de cada servei.": "The prices shown on the website and in the calculator are for guidance only and are not a binding offer. The final price is given in writing before each service.",
    "Propietat intel·lectual": "Intellectual property",
    "Els textos, les imatges i el disseny d'aquesta web són de [RAÓ SOCIAL] o s'hi fan servir amb permís. Les tipografies tenen llicència SIL Open Font License.": "The text, images and design of this website belong to [RAÓ SOCIAL] or are used with permission. The typefaces are licensed under the SIL Open Font License.",
    "Responsabilitat": "Liability",
    "Intentem que la informació d'aquesta web sigui correcta i estigui al dia, però no podem garantir que no hi hagi cap error. Si en trobes un, ens el pots dir a [CORREU DE CONTACTE].": "We try to keep the information on this website correct and up to date, but we can't guarantee there are no errors. If you find one, you can let us know at [CORREU DE CONTACTE].",
    "Llei aplicable": "Applicable law",
    "Aquesta web es regeix per la llei espanyola.": "This website is governed by Spanish law.",
    "Mudances, petits transports i guardamobles. De dilluns a dissabte, de 8 a 19 h.": "Removals, small removals and storage. Monday to Saturday, 8am to 7pm.",
    "Serveis": "Services",
    "Escriu-nos": "Write to us",
    "Privacitat": "Privacy",
    "Galetes": "Cookies",
    "Escriu-nos per WhatsApp": "Message us on WhatsApp",
    "Avís legal · Replà Mudances": "Legal notice · Replà Mudances",
    "Escriu-nos o truca'ns per a la teva mudança, un transport petit o el guardamobles.": "Message us or call us about your move, a small removal or storage.",
    "Explica'ns què et canvies i quan. Et contestem avui mateix o demà al matí.": "Tell us what you're moving and when. We'll reply today or tomorrow morning.",
    "Nom": "Name",
    "Correu": "Email",
    "Què et cal?": "What do you need?",
    "Fem servir aquestes dades només per contestar-te. Més informació a la": "We only use this information to reply to you. More information in the",
    "política de privacitat": "privacy policy",
    "Envia el missatge": "Send message",
    "Més ràpid": "Faster",
    "Si ja saps què et canvies, la calculadora et dona un preu orientatiu en un minut i te'l prepara per enviar-nos per WhatsApp.": "If you already know what you're moving, the calculator gives you an estimated price in a minute and prepares it to send us on WhatsApp.",
    "O truca'ns de dilluns a dissabte, de 8 a 19 h.": "Or call us Monday to Saturday, 8am to 7pm.",
    "Contacte · Replà Mudances": "Contact · Replà Mudances",
    "Guardamobles per setmanes o mesos, amb recollida i entrega a domicili. Per quan les dates de sortida i d'entrada no quadren.": "Storage by the week or month, with pick-up and delivery. For when your move-out and move-in dates don't match up.",
    "Per quan has de deixar el pis vell abans que et donin les claus del nou, o per a una reforma. Ho recollim, ho guardem i t'ho tornem.": "For when you have to leave your old flat before you get the keys to the new one, or for a renovation. We collect it, store it and bring it back.",
    "Demana preu": "Get a price",
    "Truca al 600 000 000": "Call 600 000 000",
    "Com funciona": "How it works",
    "Ho carreguem com en una mudança, ho guardem en caixes de fusta tancades i, quan ens ho dius, t'ho portem al pis nou.": "We load it like a removal, store it in closed wooden boxes and, when you tell us, bring it to your new flat.",
    "Caixes de fusta tancades.": "Closed wooden boxes.",
    "Cada client té les seves. Ningú més hi toca": "Each customer has their own. No one else touches them",
    "Magatzem vigilat.": "Monitored warehouse.",
    "Sec, net i amb alarma": "Dry, clean and alarmed",
    "Per setmanes o mesos.": "By the week or month.",
    "Sense permanència mínima llarga": "No long minimum stay",
    "Inventari.": "Inventory.",
    "Et donem la llista del que hi ha guardat": "We give you a list of what's stored",
    "Pots venir a buscar alguna cosa.": "You can come and collect something.",
    "Avisant un dia abans": "Just let us know a day ahead",
    "Quant costa": "How much it costs",
    "Es paga pel volum i pel temps. Un pis de dues habitacions ocupa uns 20 metres cúbics.": "You pay by volume and time. A two-bedroom flat takes up about 20 cubic metres.",
    "Preus orientatius": "Estimated prices",
    "Per metre cúbic i mes": "Per cubic metre and month",
    "des de 9 €": "from 9 €",
    "Pis de 2 habitacions (uns 20 m³)": "2-bedroom flat (about 20 m³)",
    "des de 180 €/mes": "from 180 €/month",
    "Recollida i entrega": "Pick-up and delivery",
    "com una mudança": "like a removal",
    "Preus d'exemple, IVA a part. Si ho combines amb la mudança, la recollida ja hi va inclosa.": "Example prices, VAT not included. If you combine it with a removal, pick-up is already included.",
    "Preguntes que ens fan": "Questions we get asked",
    "Està assegurat el que guardeu?": "Do you insure what you store?",
    "Sí, mentre és al magatzem i durant el transport.": "Yes, both while it's in the warehouse and during transport.",
    "Quant de temps mínim?": "What's the minimum time?",
    "Una setmana. Després es paga per mesos, i pots acabar quan vulguis avisant uns dies abans.": "One week. After that you pay by the month, and you can finish whenever you like by letting us know a few days ahead.",
    "Puc guardar-hi només uns quants mobles?": "Can I store just a few pieces of furniture?",
    "Sí. Si és poca cosa, ho compartim en una caixa gran amb separació, i pagues només el que ocupa.": "Yes. If it's not much, we share it in a large box with dividers, and you only pay for the space it takes up.",
    "Què no s'hi pot guardar?": "What can't be stored?",
    "Menjar, plantes, líquids inflamables ni res de valor com joies o diners.": "Food, plants, flammable liquids or anything valuable like jewellery or money.",
    "També fem": "We also do",
    "Mudances de pis i d'oficina": "Home and office removals",
    "Les dates no et quadren?": "Dates don't line up?",
    "Explica'ns quant de temps i què cal guardar, i et diem el preu.": "Tell us how long and what you need to store, and we'll give you a price.",
    "Guardamobles · Replà Mudances": "Storage · Replà Mudances",
    "Mudances de pis i d'oficina, petits transports i guardamobles amb preu tancat per escrit. Calcula el preu de la teva mudança en un minut.": "Home and office removals, small removals and storage with a fixed price in writing. Calculate the price of your move in a minute.",
    "Ens emportem la casa i te la deixem muntada al pis nou.": "We take your home and set it up in your new flat.",
    "Mudances de pis i d'oficina amb preu tancat per escrit. Protegim l'escala, desmuntem i tornem a muntar, i ens emportem els cartrons.": "Home and office removals with a fixed price in writing. We protect the stairs, take furniture apart and put it back together, and take the cardboard away.",
    "Calcula el preu en 1 minut": "Calculate the price in 1 minute",
    "Què et canvies?": "What are you moving?",
    "Tria-ho i en quatre preguntes més tens un preu orientatiu. Sense trucades ni esperar que et contestin.": "Choose it and four more questions give you an estimated price. No calls, no waiting for a reply.",
    "Estudi o 1 habitació": "Studio or 1 bedroom",
    "Unes 15–25 caixes i pocs mobles": "About 15–25 boxes and a few pieces of furniture",
    "Pis de 2 o 3 habitacions": "2 or 3-bedroom flat",
    "El cas més habitual": "The most common case",
    "Pis gran o casa": "Large flat or house",
    "4 habitacions o més": "4 bedrooms or more",
    "Només uns mobles": "Just a few pieces of furniture",
    "Un sofà, un armari, una compra grossa": "A sofa, a wardrobe, a big purchase",
    "El dia de la mudança, hora a hora": "Moving day, hour by hour",
    "Un pis de dues habitacions a la mateixa ciutat. Abans del dia ja t'hem portat les caixes i hem demanat el permís per aparcar davant del portal.": "A two-bedroom flat in the same city. Before the day, we've already brought you the boxes and requested the parking permit outside the building.",
    "Com treballem": "How we work",
    "Arribem i protegim": "We arrive and protect",
    "Cartró a terra, mantes a la barana i a l'ascensor. La comunitat queda igual que estava.": "Cardboard on the floor, blankets on the handrail and in the lift. The building is left just as it was.",
    "Desmuntem el que no passa": "We take apart what doesn't fit",
    "Llits, armaris i taules grans. Els cargols van en una bossa enganxada a cada peça.": "Beds, wardrobes and large tables. The screws go in a bag taped to each piece.",
    "Carreguem": "We load",
    "Cada caixa porta escrita l'habitació on va. Els mobles, embolicats en mantes i lligats amb cinta.": "Each box has the room it's going to written on it. Furniture is wrapped in blankets and tied with tape.",
    "Descarreguem al pis nou": "We unload at the new flat",
    "Tu ens dius on va cada cosa. Les caixes queden a la seva habitació, no totes al menjador.": "You tell us where everything goes. Boxes go in the right room, not all dumped in the living room.",
    "Muntem i col·loquem": "We assemble and arrange",
    "Llits muntats, armaris a lloc i la tele penjada si ens ho has demanat.": "Beds assembled, wardrobes in place, and the TV mounted if you've asked us to.",
    "Ens ho emportem tot": "We take it all away",
    "Cartrons, plàstics i el que no vulguis. Tu et quedes amb les claus i el pis net.": "Cardboard, plastic and anything you don't want. You keep the keys and a clean flat.",
    "Què inclou el preu": "What's included in the price",
    "El que signem abans de la mudança": "What we sign before the move",
    "Preu tancat per escrit": "Fixed price in writing",
    "Si el dia hi ha les coses que vam dir, pagues el que vam dir.": "If on the day there's what we agreed, you pay what we agreed.",
    "Assegurança de la càrrega": "Insurance for the load",
    "Si es trenca alguna cosa per culpa nostra, la paguem nosaltres.": "If something breaks because of us, we pay for it.",
    "Escala i ascensor protegits": "Stairs and lift protected",
    "Als dos edificis, el de sortida i el d'arribada.": "At both buildings, the one you're leaving and the one you're moving into.",
    "Permís d'aparcament": "Parking permit",
    "El demanem nosaltres a l'ajuntament, amb temps.": "We apply for it with the council, well in advance.",
    "Equip propi": "Our own team",
    "Els mateixos que venen a veure el pis són els que fan la mudança.": "The same people who come to see your flat are the ones who do the move.",
    "Hora d'arribada concreta": "A specific arrival time",
    "Una franja de 30 minuts, no «al matí».": "A 30-minute window, not just \"in the morning\".",
    "No hi entra:": "Not included:",
    "l'elevador exterior quan un moble no passa per l'escala, ni el guardamobles. Si cal, t'ho diem abans i ho veus escrit al pressupost.": "the external hoist for furniture that doesn't fit down the stairs, or storage. If needed, we'll tell you beforehand and you'll see it in writing in the quote.",
    "Signatura del client": "Customer signature",
    "Què fem": "What we do",
    "Dos operaris traslladen un sofà embolicat amb una manta pel vestíbul d'un edifici": "Two removal workers carry a sofa wrapped in a blanket through a building's lobby",
    "Del pis vell al nou, amb tot desmuntat, protegit i tornat a muntar.": "From your old flat to the new one, with everything taken apart, protected and put back together.",
    "Veure mudances": "See removals",
    "Furgoneta petita amb un armari embolicat i caixes lligades amb cintes": "Small van with a wrapped wardrobe and boxes tied with tape",
    "Un sofà, un armari o la compra de la botiga de mobles.": "A sofa, a wardrobe, or your furniture-shop delivery.",
    "Veure transports": "See small removals",
    "Magatzem net amb caixes de fusta sobre palets i mobles tapats": "Clean warehouse with wooden boxes on pallets and covered furniture",
    "Per quan les dates de sortida i d'entrada no quadren.": "For when your move-out and move-in dates don't match up.",
    "Veure guardamobles": "See storage",
    "Serveis que s'hi poden afegir": "Services you can add",
    "També:": "Also:",
    "Embalatge de tota la casa": "Packing the whole house",
    "Desmuntar i muntar mobles": "Taking apart and assembling furniture",
    "Buidatge de pisos": "Flat clearance",
    "Elevador exterior": "External hoist",
    "Mudances fetes": "Removals we've done",
    "Furgoneta carregada: caixes apilades i mobles embolicats amb mantes i cintes": "Loaded van: stacked boxes and furniture wrapped in blankets and tape",
    "Pis de 3 habitacions.": "3-bedroom flat.",
    "Tot en un sol viatge.": "Everything in a single trip.",
    "Escala estreta protegida amb cartró i mantes a la barana, amb caixes al replà": "Narrow staircase protected with cardboard and blankets on the handrail, with boxes on the landing",
    "Un quart sense ascensor.": "A fourth-floor flat with no lift.",
    "Barana i esglaons protegits.": "Handrail and steps protected.",
    "Oficina durant el trasllat, amb cadires embolicades i caixes en un carro": "Office during the move, with wrapped chairs and boxes on a trolley",
    "Oficina de 12 llocs.": "12-desk office.",
    "Fet en dissabte.": "Done on a Saturday.",
    "Elevador exterior aixecat fins a un balcó amb un sofà embolicat": "External hoist raised to a balcony with a wrapped sofa",
    "Un sofà que no passava per l'escala.": "A sofa that didn't fit down the stairs.",
    "Per la finestra.": "Through the window.",
    "Caixa de cartró amb plats i gots embolicats amb paper": "Cardboard box with plates and glasses wrapped in paper",
    "La cuina.": "The kitchen.",
    "Cada got, embolicat a part.": "Each glass, wrapped separately.",
    "Pis buit i escombrat després de la mudança, amb sol entrant per la finestra": "Empty, swept flat after the move, with sunlight coming through the window",
    "El pis vell.": "The old flat.",
    "Buit i escombrat per tornar les claus.": "Empty and swept, ready to hand back the keys.",
    "Dos operaris d'esquena camí de la furgoneta, un empenyent un carretó amb caixes": "Two removal workers walking to the van from behind, one pushing a trolley of boxes",
    "Primera mudança del dia, a les vuit.": "First move of the day, at eight.",
    "Som la Pau i la Núria": "We're Pau and Núria",
    "Vam començar amb una furgoneta llogada i les mudances dels amics. Ara som més i tenim camions propis, però ho seguim fent igual: veiem el pis abans, et diem el preu per escrit i el dia hi som a l'hora.": "We started with a rented van and our friends' removals. Now there are more of us and we have our own lorries, but we still do it the same way: we see the flat beforehand, give you the price in writing, and we're on time on the day.",
    "La Núria fa els pressupostos i organitza els dies. La Pau porta l'equip i és qui hi ha el dia de la mudança, de la primera caixa a l'última.": "Núria puts together the quotes and organises the schedule. Pau leads the team and is there on moving day, from the first box to the last.",
    "Què diuen de nosaltres": "What people say about us",
    "Ressenyes d'exemple": "Example reviews",
    "fa 2 setmanes": "2 weeks ago",
    "5 de 5 estrelles": "5 out of 5 stars",
    "Un tercer sense ascensor a un quart sense ascensor, i a les dues havien acabat. El preu va ser el del paper, ni un euro més.": "From a third floor with no lift to a fourth floor with no lift, and they were done by two o'clock. The price was exactly what was on paper, not a euro more.",
    "fa 1 mes": "1 month ago",
    "Vam traslladar l'oficina un dissabte i el dilluns tothom tenia l'ordinador endollat. Les caixes anaven marcades per taula.": "We moved the office on a Saturday and by Monday everyone had their computer plugged in. The boxes were labelled by desk.",
    "fa 3 mesos": "3 months ago",
    "4 de 5 estrelles": "4 out of 5 stars",
    "Van arribar vint minuts tard per un tall al carrer, però m'havien avisat per WhatsApp. Tot arribat sencer, fins i tot el mirall gran.": "They arrived twenty minutes late because of a road closure, but they'd let me know on WhatsApp. Everything arrived in one piece, even the big mirror.",
    "Tens data de claus? Mira quant et costarà.": "Got a date for the keys? See how much it'll cost.",
    "Cinc preguntes, un preu orientatiu i el resum a punt per enviar-nos per WhatsApp.": "Five questions, an estimated price, and a summary ready to send us on WhatsApp.",
    "Foto ampliada": "Enlarged photo",
    "Tanca": "Close",
    "Replà Mudances · Mudances de pis, petits transports i guardamobles": "Replà Mudances · Home removals, small removals and storage",
    "Mudances de pis i d'oficina amb preu tancat per escrit, assegurança de la càrrega, muntatge de mobles i permís d'aparcament inclosos.": "Home and office removals with a fixed price in writing, load insurance, furniture assembly and parking permit included.",
    "Del pis vell al nou en un dia, amb els mobles muntats i les caixes a la seva habitació.": "From your old flat to the new one in a day, with furniture assembled and boxes in the right room.",
    "Una mudança de pis sencera, o la d'una oficina petita un dissabte perquè el dilluns es pugui treballar.": "A whole flat move, or a small office move on a Saturday so work can start again on Monday.",
    "Visita o videotrucada.": "Visit or video call.",
    "Veiem què hi ha i com són els accessos abans de donar-te el preu": "We see what's there and what the access is like before giving you the price",
    "Protecció.": "Protection.",
    "Cartró a terra i mantes a l'escala i a l'ascensor, als dos edificis": "Cardboard on the floor and blankets on the stairs and lift, at both buildings",
    "Desmuntar i muntar.": "Taking apart and assembling.",
    "Llits, armaris, taules i el que no passi sencer per la porta": "Beds, wardrobes, tables and anything that won't fit through the door in one piece",
    "Càrrega amb mantes i cintes.": "Loading with blankets and tape.",
    "Res va solt dins del camió": "Nothing rattles loose inside the lorry",
    "Permís d'aparcament.": "Parking permit.",
    "El demanem nosaltres amb el temps que demana cada ajuntament": "We apply for it with whatever notice each council requires",
    "Retirada de cartrons.": "Cardboard removal.",
    "Quan acabem, ens emportem el material d'embalar": "When we finish, we take the packing material away",
    "Com ho fem": "How we do it",
    "Ens expliques què et canvies": "Tell us what you're moving",
    "Amb la calculadora, per WhatsApp o per telèfon. Si vols, fem una videotrucada i ens ensenyes el pis.": "With the calculator, on WhatsApp or by phone. If you like, we can video call and you show us the flat.",
    "Et donem el preu per escrit": "We give you the price in writing",
    "Amb tot el que inclou i el que no. Si hi ha un moble que no passa per l'escala, ja ho diem aquí.": "With everything it includes and what it doesn't. If there's a piece of furniture that won't fit down the stairs, we say so here.",
    "Et portem les caixes": "We bring you the boxes",
    "Uns dies abans, perquè puguis anar embalant. O ho embalem nosaltres.": "A few days beforehand, so you can start packing. Or we can pack it for you.",
    "El dia de la mudança": "Moving day",
    "Hi arribem a l'hora pactada i no marxem fins que els mobles estan muntats.": "We arrive at the agreed time and we don't leave until the furniture is assembled.",
    "Depèn sobretot de quantes coses hi ha i de com són els accessos. La distància pesa menys del que sembla.": "It mostly depends on how much stuff there is and what the access is like. Distance matters less than you'd think.",
    "Calcula el teu preu": "Calculate your price",
    "Preus orientatius dins la mateixa ciutat": "Estimated prices within the same city",
    "des de 260 €": "from 260 €",
    "des de 510 €": "from 510 €",
    "des de 880 €": "from 880 €",
    "Oficina petita": "Small office",
    "segons els llocs de treball": "depending on the number of desks",
    "Preus d'exemple, IVA a part. Sense ascensor o amb embalatge i muntatge, el preu puja. El tancat te'l donem per escrit.": "Example prices, VAT not included. Without a lift, or with packing and assembly, the price goes up. We'll give you the fixed price in writing.",
    "El preu és tancat?": "Is the price fixed?",
    "Sí. Te'l donem per escrit després de veure el pis o una videotrucada. Només canvia si el dia hi ha coses que no hi eren, i en aquest cas t'ho diem abans de carregar-les.": "Yes. We give it to you in writing after seeing the flat or a video call. It only changes if there's something extra on the day, and in that case we tell you before loading it.",
    "I si es trenca alguna cosa?": "What if something breaks?",
    "Tota la càrrega va assegurada. Si es trenca o es fa malbé alguna cosa per culpa nostra, la reparem o la paguem. Ho deixem escrit al pressupost.": "The whole load is insured. If something breaks or is damaged because of us, we repair it or pay for it. We put it in writing in the quote.",
    "Qui demana el permís per aparcar el camió?": "Who applies for the permit to park the lorry?",
    "Nosaltres. Cada ajuntament té els seus terminis (sovint una setmana), per això és millor reservar amb temps.": "We do. Each council has its own timeframes (often a week), so it's best to book ahead.",
    "I si no hi ha ascensor o el sofà no passa per l'escala?": "What if there's no lift or the sofa won't fit down the stairs?",
    "Sense ascensor ho pugem a peu i ja ho comptem al preu. Si un moble no passa, fem servir un elevador exterior per la finestra o el balcó, i t'ho diem al pressupost.": "Without a lift, we carry it up the stairs and that's already factored into the price. If a piece of furniture doesn't fit, we use an external hoist through the window or balcony, and we tell you in the quote.",
    "Amb quanta antelació he de reservar?": "How far in advance do I need to book?",
    "Amb dues o tres setmanes vas bé. A final de mes i a l'estiu s'omple abans. Si és urgent, pregunta: de vegades hi ha forats.": "Two or three weeks ahead is fine. It fills up faster at the end of the month and in summer. If it's urgent, ask anyway: sometimes there's a gap.",
    "Us podeu endur el que no vull?": "Can you take away what I don't want?",
    "Sí. Ens emportem mobles i trastos que no vulguis traslladar i els portem al punt verd o a entitats que els aprofiten. Té un cost a part.": "Yes. We take away furniture and junk you don't want to move and take it to the recycling centre or to charities that can use it. There's an extra cost for this.",
    "Tens data de claus?": "Got a date for the keys?",
    "Calcula el preu orientatiu i envia'ns el resum per WhatsApp.": "Calculate an estimated price and send us the summary on WhatsApp.",
    "Mudances de pis i d'oficina · Replà Mudances": "Flat and office removals · Replà Mudances",
    "Transport de mobles solts i compres grans: un sofà, un armari o la compra de la botiga de mobles, pujat i muntat a casa.": "Transport for loose furniture and large purchases: a sofa, a wardrobe or your furniture shop order, carried up and assembled at home.",
    "Un sofà, un armari o la compra de la botiga de mobles. Ho recollim, ho pugem i, si cal, ho muntem.": "A sofa, a wardrobe or your furniture shop order. We collect it, carry it up and, if needed, assemble it.",
    "Per a quan no és una mudança": "For when it's not a full move",
    "Quan només són uns quants mobles, no cal llogar una furgoneta ni demanar favors a ningú un dissabte.": "When it's just a few pieces of furniture, there's no need to hire a van or ask friends for favours on a Saturday.",
    "Mobles solts.": "Loose furniture.",
    "Un sofà, un llit, una calaixera o l'armari de l'àvia": "A sofa, a bed, a chest of drawers or your grandmother's wardrobe",
    "Compres grans.": "Large purchases.",
    "Recollim a la botiga o al magatzem i t'ho portem a casa": "We collect from the shop or warehouse and bring it to your home",
    "Muntatge.": "Assembly.",
    "Els mobles de paquet pla te'ls deixem muntats": "We leave flat-pack furniture fully assembled",
    "Entre pisos del mateix edifici.": "Between flats in the same building.",
    "També, i amb el mateix compte que en una mudança": "That too, with the same care as in a full move",
    "Un transport petit dins la mateixa ciutat surt a partir de 80 €. Depèn de quantes peces són, de la distància i de si hi ha ascensor.": "A small transport within the same city starts from 80 €. It depends on how many pieces there are, the distance and whether there's a lift.",
    "Exemples orientatius": "Example prices",
    "Un sofà, mateixa ciutat, amb ascensor": "A sofa, same city, with lift",
    "des de 80 €": "from 80 €",
    "Compra d'una botiga de mobles, muntada": "Furniture shop order, assembled",
    "des de 150 €": "from 150 €",
    "Tres o quatre mobles, sense ascensor": "Three or four pieces of furniture, no lift",
    "des de 180 €": "from 180 €",
    "Preus d'exemple, IVA a part.": "Example prices, VAT not included.",
    "Veniu per un sol moble?": "Do you come for just one item?",
    "Sí. Si és dins la zona, venim per un sol moble. Ho veuràs al preu.": "Yes. If it's within our area, we'll come for just one item. You'll see it reflected in the price.",
    "Podeu recollir-ho a la botiga?": "Can you collect it from the shop?",
    "Sí. Ens passes el número de comanda i l'hora de recollida, i ho anem a buscar nosaltres.": "Yes. Send us the order number and collection time, and we'll go and pick it up.",
    "Ho pugeu fins a dins del pis?": "Do you carry it right into the flat?",
    "Sí, fins a l'habitació on va. No ho deixem al portal.": "Yes, right to the room it belongs in. We don't leave it in the entrance hall.",
    "Munteu mobles de paquet pla?": "Do you assemble flat-pack furniture?",
    "Sí, i ens emportem els cartrons. Si ja el tens a casa, també et podem venir només a muntar.": "Yes, and we take the boxes away with us. If you already have it at home, we can also come just to assemble it.",
    "Només són uns mobles?": "Is it just a few pieces of furniture?",
    "En un minut saps quant et costarà portar-los.": "In a minute you'll know how much it'll cost to move them.",
    "Petits transports · Replà Mudances": "Small removals · Replà Mudances",
    "Política de galetes de Replà Mudances.": "Replà Mudances cookie policy.",
    "Política de galetes": "Cookie policy",
    "Galetes nostres": "Our own cookies",
    "Aquesta web no fa servir galetes pròpies ni d'analítica. Les tipografies s'allotgen a la mateixa web i no es demanen a cap servei extern.": "This website doesn't use its own or analytics cookies. The fonts are hosted on the website itself and aren't requested from any external service.",
    "Emmagatzematge del navegador": "Browser storage",
    "La calculadora guarda les teves respostes a l'emmagatzematge de sessió del navegador perquè no les perdis si recarregues la pàgina. S'esborra sol quan tanques la pestanya i no s'envia enlloc.": "The calculator saves your answers in the browser's session storage so you don't lose them if you reload the page. It clears itself when you close the tab and is never sent anywhere.",
    "Serveis de tercers": "Third-party services",
    "Només a la calculadora, quan arribes al pas del correu, per comprovar que no ets un robot. Pot fer servir dades tècniques del navegador.": "Only in the calculator, when you reach the email step, to check you're not a robot. It may use technical browser data.",
    "Només si envies el formulari de contacte, i només rep el que hi escrius.": "Only if you submit the contact form, and it only receives what you write in it.",
    "Els botons de WhatsApp obren l'aplicació o la web de WhatsApp. A partir d'aquí s'aplica la política de WhatsApp.": "The WhatsApp buttons open the WhatsApp app or website. From there, WhatsApp's own policy applies.",
    "Política de galetes · Replà Mudances": "Cookie policy · Replà Mudances",
    "Política de privacitat de Replà Mudances.": "Replà Mudances privacy policy.",
    "Política de privacitat": "Privacy policy",
    "Responsable": "Data controller",
    "[RAÓ SOCIAL], NIF [NIF], [DOMICILI]. Contacte per a qüestions de privacitat: [CORREU DE CONTACTE].": "[RAÓ SOCIAL], NIF [NIF], [DOMICILI]. Contact for privacy questions: [CORREU DE CONTACTE].",
    "Quines dades recollim i per a què": "What data we collect and why",
    "Formulari de contacte.": "Contact form.",
    "Nom, correu i el missatge, per contestar-te. El formulari el gestiona Formspree, Inc. (Estats Units), que actua com a encarregat del tractament i ens fa arribar el missatge.": "Name, email and message, so we can reply to you. The form is managed by Formspree, Inc. (United States), which acts as data processor and forwards the message to us.",
    "Calculadora de preu.": "Price calculator.",
    "Per ensenyar-te el preu et demanem el correu i t'hi enviem un codi de verificació amb Brevo (Sendinblue SAS, Unió Europea). El codi es guarda xifrat un màxim de 10 minuts.": "To show you the price we ask for your email and send you a verification code with Brevo (Sendinblue SAS, European Union). The code is stored encrypted for a maximum of 10 minutes.",
    "Per comprovar que qui fa servir la calculadora no és un robot, fem servir Cloudflare Turnstile, que pot tractar dades tècniques com la teva adreça IP. Només es carrega quan arribes al pas del correu.": "To check that whoever is using the calculator isn't a robot, we use Cloudflare Turnstile, which may process technical data such as your IP address. It only loads when you reach the email step.",
    "Quan verifiques el codi, guardem el correu, les respostes de la calculadora, el preu orientatiu, l'idioma de la pàgina i la data en una base de dades de Cloudflare (D1), per poder-te contactar sobre aquesta mudança. T'enviem un correu amb el resum i ens arriba un avís a nosaltres, tots dos amb Brevo.": "When you verify the code, we store your email, the calculator answers, the estimated price, the page language and the date in a Cloudflare database (D1), so we can contact you about this move. We send you an email with the summary and an alert reaches us too, both via Brevo.",
    "Base legal": "Legal basis",
    "El teu consentiment, quan ens escrius o fas servir la calculadora, i l'interès a contestar la sol·licitud que ens fas.": "Your consent, when you write to us or use the calculator, and our interest in responding to your request.",
    "Quant de temps les guardem": "How long we keep it",
    "El temps necessari per atendre la teva sol·licitud i, com a màxim, un any des de l'últim contacte si no n'hi ha cap servei contractat.": "The time needed to handle your request and, at most, one year from the last contact if no service has been contracted.",
    "Els teus drets": "Your rights",
    "Pots demanar accedir a les teves dades, corregir-les, esborrar-les, limitar-ne o oposar-te al tractament i portar-les a un altre lloc escrivint a [CORREU DE CONTACTE]. Si creus que no les tractem bé, pots reclamar a l'Agència Espanyola de Protecció de Dades (aepd.es).": "You can ask to access your data, correct it, delete it, restrict or object to its processing, and take it elsewhere by writing to [CORREU DE CONTACTE]. If you think we're not handling it properly, you can complain to the Spanish Data Protection Agency (aepd.es).",
    "Política de privacitat · Replà Mudances": "Privacy policy · Replà Mudances",
    "Calcula en un minut quant et pot costar la mudança o el transport dels teus mobles. Sense compromís.": "Work out in a minute how much your move or furniture transport could cost. No obligation.",
    "Enrere": "Back",
    "Progrés": "Progress",
    "Les teves respostes": "Your answers",
    "Calcula el preu en 1 minut. Sense compromís.": "Work out the price in 1 minute. No obligation.",
    "Quants quilòmetres hi ha entre les dues adreces?": "How many kilometres are there between the two addresses?",
    "Si és al mateix poble o barri, deixa-ho entre 1 i 5.": "If it's in the same town or neighbourhood, leave it between 1 and 5.",
    "Quilòmetres": "Kilometres",
    "Continua": "Continue",
    "Com són els accessos?": "What are the access conditions like?",
    "Pensa en el pis d'on surts i en el pis on vas.": "Think about the flat you're leaving and the flat you're moving into.",
    "Hi ha ascensor als dos llocs": "There's a lift in both places",
    "O és una planta baixa.": "Or it's a ground floor.",
    "Escales en un dels dos": "Stairs in one of the two",
    "A l'altre hi ha ascensor.": "The other one has a lift.",
    "Escales als dos llocs": "Stairs in both places",
    "Sense ascensor enlloc.": "No lift anywhere.",
    "Què vols que fem nosaltres?": "What do you want us to do?",
    "Només el transport": "Just the transport",
    "Tu embales i desmuntes. Nosaltres carreguem i ho portem.": "You pack and disassemble. We load it and take it there.",
    "També embalar i muntar": "Packing and assembly too",
    "Embalem, desmuntem i tornem a muntar els mobles.": "We pack, disassemble and reassemble the furniture.",
    "Tot, fins i tot desembalar": "Everything, including unpacking",
    "Arribes al pis nou i ja està tot al seu lloc.": "You arrive at the new flat and everything's already in place.",
    "Quan et va bé?": "When suits you?",
    "Tinc una data fixa": "I have a fixed date",
    "Soc flexible": "I'm flexible",
    "Si ens deixes triar el dia, surt més barat.": "If you let us choose the day, it works out cheaper.",
    "Només miro preus": "Just checking prices",
    "El teu preu ja està calculat": "Your price is ready",
    "Verifica el correu per veure'l. T'hi enviarem també el resum.": "Verify your email to see it. We'll also send the summary there.",
    "El teu correu": "Your email",
    "Envia'm el codi": "Send me the code",
    "Guardem el correu i les respostes per poder-te contactar sobre aquesta mudança. Més informació a la": "We store your email and answers so we can contact you about this move. More information in the",
    "Escriu el codi": "Enter the code",
    "L'hem enviat a": "We've sent it to",
    ". Caduca d'aquí a 10 minuts.": ". It expires in 10 minutes.",
    "Codi de 6 xifres": "6-digit code",
    "Xifra 1": "Digit 1",
    "Xifra 2": "Digit 2",
    "Xifra 3": "Digit 3",
    "Xifra 4": "Digit 4",
    "Xifra 5": "Digit 5",
    "Xifra 6": "Digit 6",
    "Torna a enviar el codi": "Resend the code",
    "Canvia el correu": "Change email",
    "Preu orientatiu de la teva mudança": "Estimated price for your move",
    "IVA a part. El preu tancat te'l donem per escrit abans del dia de la mudança.": "VAT not included. We'll give you the final price in writing before the day of the move.",
    "També t'hem enviat aquest resum al correu.": "We've also sent this summary to your email.",
    "Envia'ns la mudança per WhatsApp": "Send us your move via WhatsApp",
    "S'obrirà WhatsApp amb el resum ja escrit. Només l'has d'enviar.": "WhatsApp will open with the summary already written. Just send it.",
    "Prefereixo que m'escriviu": "I'd rather you wrote to me",
    "Calcula una altra mudança": "Work out another move",
    "La furgoneta és buida. Respon i s'anirà omplint.": "The van is empty. Answer and it'll start filling up.",
    "Calcula el preu de la mudança · Replà Mudances": "Work out the price of your move · Replà Mudances",
    "Roba": "Clothes",
    "Cuina": "Kitchen",
    "Llibres": "Books",
    "Menjador": "Dining room",
    "Bany": "Bathroom",
    "Llençols": "Bedding",
    "Joguines": "Toys",
    "Traster": "Storage",
    "Sofà": "Sofa",
    "Armari": "Wardrobe",
    "Eines": "Tools",
    "Paper": "Paperwork",
    "Mantes": "Blankets",
    "Carregada i a punt per sortir.": "Loaded and ready to go.",
    "Caixes a la furgoneta:": "Boxes in the van:",
    "Canvia aquesta resposta": "Change this answer",
    "Escriu un correu vàlid, per exemple nom@gmail.com.": "Enter a valid email, for example name@gmail.com.",
    "Espera un moment que acabi la comprovació de seguretat i torna-hi.": "Wait a moment for the security check to finish and try again.",
    "Enviant…": "Sending…",
    "Has demanat massa codis. Espera uns minuts i torna-hi.": "You've requested too many codes. Wait a few minutes and try again.",
    "No hem pogut confirmar que no ets un robot. Torna-hi.": "We couldn't confirm you're not a robot. Try again.",
    "No hem pogut enviar el codi. Torna-hi d'aquí a uns minuts.": "We couldn't send the code. Try again in a few minutes.",
    "El codi ha caducat. Demana'n un de nou.": "The code has expired. Request a new one.",
    "Massa intents. Demana un codi nou.": "Too many attempts. Request a new code.",
    "El codi no és correcte. Revisa'l i torna a escriure'l.": "The code isn't correct. Check it and enter it again.",
    "No hem pogut comprovar el codi. Torna-hi.": "We couldn't check the code. Try again.",
    "Hola, vull fer una mudança. He fet servir la calculadora de la web: {resum}. Preu orientatiu: {rang}. Em podeu dir un dia?": "Hi, I'd like to book a move. I've used the calculator on the website: {resum}. Estimated price: {rang}. Could you tell me a date?",
    "Escriu el teu nom.": "Enter your name.",
    "Escriu un correu vàlid.": "Enter a valid email.",
    "Explica'ns què et cal.": "Tell us what you need.",
    "Rebut. Et contestem avui mateix o demà al matí.": "Received. We'll reply today or tomorrow morning.",
    "No s'ha pogut enviar. Truca'ns al 600 000 000 i t'atenem directament.": "It couldn't be sent. Call us on 600 000 000 and we'll help you directly."
  }
};
/* ── TRAD:fi ── */

/* Amb el diccionari carregat, el motor ja pot fer la feina. */
if (window.I18N) window.I18N.inicia();
